### ISSUE TITLE
Missing Enterprise_E200 sku with RedisEnterprise / API Version 2024-06-01-preview

### ISSUE THREAD

**Issue by aiqiaoy** [hashicorp/go-azure-sdk#1121]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

Redis Enterprise

### API Versions Used

2024-06-01-preview

### Description

`2024-06-01-preview` is missing `Enterprise_E200` sku which was supported in `2023-10-01-preview` 

https://github.com/hashicorp/go-azure-sdk/blob/2c82270fdd193c987ed3632082806e3c6fe000c1/resource-manager/redisenterprise/2024-06-01-preview/redisenterprise/constants.go#L646-L658

https://github.com/hashicorp/go-azure-sdk/blob/2c82270fdd193c987ed3632082806e3c6fe000c1/resource-manager/redisenterprise/2023-10-01-preview/redisenterprise/constants.go#L613

**Comment by stephybun** [comment]
Hey @aiqiaoy,

This SDK is generated by [hashicorp/Pandora](https://github.com/hashicorp/pandora) which consumes the Microsoft Rest API Specs. Looking at the spec the issue seems to be that the upstream data doesn't define the `Enterprise_E200` sku anymore 

`2023-10-01-preview`
https://github.com/Azure/azure-rest-api-specs/blob/2afa5b356adf6cf51209d2cf28d38644c69d9832/specification/redisenterprise/resource-manager/Microsoft.Cache/preview/2023-10-01-preview/redisenterprise.json#L1918-L1929

`2024-06-01-preview`
https://github.com/Azure/azure-rest-api-specs/blob/2afa5b356adf6cf51209d2cf28d38644c69d9832/specification/redisenterprise/resource-manager/Microsoft.Cache/preview/2024-06-01-preview/redisenterprise.json#L1405-L1415

I'm going to close this since we can't add this missing sku into the definition as it would just be overwritten by the generation, but I would suggest opening an issue on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) to get this added or looked at.
