### ISSUE TITLE
Support for Compute Resource Skus / 2021-07-01

### ISSUE THREAD

**Issue by dennis-menge** [hashicorp/go-azure-sdk#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

Compute / Resource Skus

### API Versions Required

2021-07-01

### References

https://docs.microsoft.com/en-us/rest/api/compute/resource-skus

**Comment by tombuildsstuff** [comment]
The `Compute` @ `2021-07-01` SDK is now available: https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/compute/2021-07-01

[Documentation for this API Version can be found here](https://pkg.go.dev/github.com/hashicorp/go-azure-sdk@v0.20220915.1151935/resource-manager/compute/2021-07-01/skus) - closing this out since this is now available.
