### ISSUE TITLE
Question about Insights / API Version 2022-06-01

### ISSUE THREAD

**Issue by simaotwx** [hashicorp/go-azure-sdk#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

Insights

### API Versions Used

2022-06-01

### Description

See: https://github.com/hashicorp/go-azure-sdk/blob/8773020097e59361f283a746ba73abcab30f5d1d/resource-manager/insights/2022-06-01/datacollectionrules/constants.go#L248

Why is only text format supported?
What does the text format mean for the log files?

From what I have read, log files need to be JSON: https://learn.microsoft.com/en-us/azure/azure-monitor/logs/tutorial-logs-ingestion-portal?WT.mc_id=Portal-Microsoft_Azure_Support

This confuses me, especially because a `record_start_timestamp_format` has to be specified (and I still don't know what this means for my log files).

So, how do my log files need to look like for this to work?

I am using Terraform and the Terraform provider for AzureRM uses `github.com/hashicorp/go-azure-sdk/resource-manager/insights/2022-06-01/datacollectionrules`.

**Comment by tombuildsstuff** [comment]
hey @simaotwx 

This SDK's ultimately generated from [the Azure API Specifications](https://github.com/Azure/azure-rest-api-specs) - which [in this case comes from this file/Enum definition](https://github.com/Azure/azure-rest-api-specs/blob/c9fd3070a45da18959192265c0e62dd34b521ab1/specification/monitor/resource-manager/Microsoft.Insights/stable/2022-06-01/dataCollectionRules_API.json#L648-L651) where only the mode `text` is defined. This also [appears to be true for the next version of the API too](https://github.com/Azure/azure-rest-api-specs/pull/22732/files#diff-0d7828bae6eba9a7b994e4c1e8ef0b7a598e7d62bf77cd74571f30e7da6e9cd6R647-R658) - so whilst I'm unfamiliar with the internals of this API, I'd suggest that specifying the JSON file contents as `text` should be sufficient here (since my guess is this could be extended to support zip files or similar in the future, hence the `text` mode).

From the SDK's perspective we're exposing all of the information available to us here, so whilst I believe this should work with the mode set to `text`, if that doesn't work I'd recommend creating one by hand (via the Portal/CLI) and confirming if this uses the value `text` - if it doesn't then that value should be added to the Enum definition within the API Definitions, so that downstream consumers (such as this SDK) can expose that information.

However since it appears that we're exposing all of the information available to us from the API Definitions, I'm going to close this issue for the moment since I don't think there's much more for us to do here - but if this does need an `enum` value added to the API Definitions - once support for that's been merged into the upstream repository, we'll generate that value - but I believe this should be doable today using the `text` value.

Thanks!

**Comment by simaotwx** [comment]
hey @tombuildsstuff, thank you for the detailed response. That makes sense. JSON is also `text` and not a binary format.

**Comment by simaotwx** [comment]
I know this is only tangentially related – but do you happen to know what `record_start_timestamp_format` means in this context? How do the logs have to look like for this to work?

**Comment by tombuildsstuff** [comment]
Honestly I don't have much context on the Service without digging into it, I'd assume that's the date time format used in the file to be parsed? I'd probably create/export one in the Portal to confirm, however.
