### ISSUE TITLE
Issue with containerservice / API Version 2023-04-02-preview

### ISSUE THREAD

**Issue by AntoineAtLeocare** [hashicorp/go-azure-sdk#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

ContainerService

### API Versions Used

2023-04-02-preview

### Description

The `overlay` in the following line should be `Overlay`: <https://github.com/hashicorp/go-azure-sdk/blob/160aab37f719af59809957ef39099010b4eada09/resource-manager/containerservice/2023-04-02-preview/managedclusters/constants.go#L741>

Same thing here: <https://github.com/hashicorp/go-azure-sdk/blob/160aab37f719af59809957ef39099010b4eada09/resource-manager/containerservice/2023-04-02-preview/managedclustersnapshots/constants.go#L154>

The issue exists for the 2023-03-02-preview API version too.

Currently, we cannot deploy an AKS cluster with `network_plugin_mode = Overlay` because of this bug:

```console
Error: `pod_cidr` and `azure` cannot be set together unless specifying `network_plugin_mode` to `overlay`
```

**Comment by stephybun** [comment]
Thanks for raising this issue @AntoineAtLeocare.

This SDK is generated from the REST API specs published by MSFT and unfortunately the casing changed in the definition.
https://github.com/Azure/azure-rest-api-specs/blob/0c26fc59fe183ad8be67196bf04beedc9b539338/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-02-02-preview/managedClusters.json#L7085-L7089
https://github.com/Azure/azure-rest-api-specs/blob/0c26fc59fe183ad8be67196bf04beedc9b539338/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-04-02-preview/managedClusters.json#L7158-L7162

As such the casing used in the SDK is correct. We just merged https://github.com/hashicorp/terraform-provider-azurerm/pull/22153 which fixes the validation check preventing creation of AKS cluster's using `overlay`.

Since this is a provider issue and a fix has been merged I'm going to go ahead and close this issue. Thanks!
