### ISSUE TITLE
HDInsight / API Version 2021-06-01 - `DisableAzureMonitorThenPoll` never stops polling

### ISSUE THREAD

**Issue by mbfrahry** [hashicorp/go-azure-sdk#518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

HDInsight

### API Versions Used

2021-06-01

### Description

[DisableAzureMonitorThenPoll](https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/hdinsight/2021-06-01/extensions/method_disableazuremonitor.go#L66) doesn't stop polling

The API is returning 

```
:status: 200
cache-control: no-cache
pragma: no-cache
content-type: application/json; charset=utf-8
content-encoding: gzip
expires: -1
vary: Accept-Encoding
x-ms-request-id: 8a5a8f82-7182-47be-94d4-a09b4b3273f6
x-ms-hdi-served-by: eastus
x-ms-correlation-request-id: 7246ed39-d7db-491a-8c3b-89766557d2c9
x-ms-ratelimit-remaining-subscription-reads: 11995
server: Microsoft-HTTPAPI/2.0
x-ms-routing-request-id: WESTUS2:20230621T222217Z:7246ed39-d7db-491a-8c3b-89766557d2c9
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
date: Wed, 21 Jun 2023 22:22:16 GMT

{"clusterMonitoringEnabled":false,"workspaceId":null}
```

I believe this is happening because the [HttpMethod](https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/hdinsight/2021-06-01/extensions/method_disableazuremonitor.go#L32) in the request is `http.MethodDelete` and the poller is waiting for it to delete but the delete is just having `clusterMonitoringEnabled` go from `true` to `false`

Before the Disable Request `clusterMonitoringEnabled` is `true` and then after the request `clusterMonitoringEnabled` is `false`.

**Comment by tombuildsstuff** [comment]
Thinking through this one, I don't think there's a way for us to handle this automatically, since this is a Delete LRO which returns a 200 OK to mark completed, whereas we're expecting a 200 OK to mean "in-progress" as in other Delete LROs.

As such whilst there is [a unique poller for handling Delete LROs](https://github.com/hashicorp/go-azure-sdk/blob/72beed903fdf8b2a6de92eb4a305c02dd5ef2a02/sdk/client/resourcemanager/poller.go#L53-L62) - I don't think this is something that the SDK can account for, since we're always going to need to unique check this one - so I think the suggestion here would be to start the LRO and then [write a custom poller](https://github.com/hashicorp/go-azure-sdk/blob/72beed903fdf8b2a6de92eb4a305c02dd5ef2a02/sdk/client/pollers/interface.go#L14-L28) to ensure the `clusterMonitoringEnabled` field gets updated to `false` - WDYT @manicminer?

**Comment by manicminer** [comment]
Agreed, a custom poller makes sense here, I don't think there's a way to infer whether the API is sending 200 for completed versus in-progress, particularly for DELETEs. Or maybe if the operation is reasonably synchronous, we forego polling?

**Comment by tombuildsstuff** [comment]
We'd need the API Definitions to state this is synchronous though, so I don't think there's much, if anything we can do in an (automated) fashion to account for that?

**Comment by tombuildsstuff** [comment]
@mbfrahry in this case you'd need to use a Custom Poller to do this, as outlined above - mind taking a look?

**Comment by tombuildsstuff** [comment]
Fixed by adding custom pollers in https://github.com/hashicorp/terraform-provider-azurerm/pull/24011
