### ISSUE TITLE
Support for DevCenter / 2023-04-01

### ISSUE THREAD

**Issue by andrew-numa-ubs** [hashicorp/go-azure-sdk#549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Name

Dev Center

### API Versions Required

2023-04-01

### References

[Dev Center REST Api Reference](https://learn.microsoft.com/en-us/rest/api/devcenter) 

[Microsoft Dev Box](https://azure.microsoft.com/en-us/products/dev-box) 

[Microsoft Dev Box Documentation](https://learn.microsoft.com/en-us/azure/dev-box/)

**Comment by tombuildsstuff** [comment]
hey @andrew-numa-ubs 

Thanks for opening this issue.

Support for this SDK is available in `hashicorp/go-azure-sdk`: https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/devcenter/2023-04-01 and a couple of these resources are shipping in the next release of `hashicorp/terraform-provider-azurerm`: https://github.com/hashicorp/terraform-provider-azurerm/pull/23538 - as such I'm going to close this issue for the moment since this is now available.

Thanks!
