### ISSUE TITLE
Issue with eventhub networkrulesets / API Version 2024-01-01

### ISSUE THREAD

**Issue by rutgersc** [hashicorp/go-azure-sdk#976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Service Used

networkrulesets

### API Versions Used

2024-01-01

### Description

I'm experimenting with trying to add `cleanup_policy` to [eventhub_resource.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/eventhub/eventhub_resource.go) in the azurerm terraform provider. In order to support this setting I had to upgrade to a newer version of the sdk: `go-azure-sdk/resource-manager/2024-01-01`

It [uses](https://github.com/hashicorp/terraform-provider-azurerm/blob/e39139bd826f27a1514f76a1c9c0b47085485102/internal/services/eventhub/eventhub_namespace_resource.go#L591) the `NamespacesGetNetworkRuleSet` from [method_namespacesgetnetworkruleset.go](https://github.com/hashicorp/go-azure-sdk/blob/main/resource-manager/eventhub/2024-01-01/networkrulesets/method_namespacesgetnetworkruleset.go), however now I'm encountering an error when trying to create an eventhubs namespace: 

```log
╷
│ Error: retrieving Network Rule Sets for Namespace (Subscription: "{id}"
│ Resource Group Name: "rutgereventhubs-rg"
│ Namespace Name: "rutgereventhubs-hub-ns"): unexpected status 400 (400 Bad Request) with error: NoRegisteredProviderFound: No registered resource provider found for location 'westeurope' and API version '2024-01-01' for type 'namespaces/networkrulesets'. The supported api-versions are '2017-04-01,
2018-01-01-preview, 2021-01-01-preview, 2021-06-01-preview, 2021-11-01, 2022-01-01-preview, 2022-10-01-preview, 2023-01-01-preview'. The supported locations are 'australiacentral, australiaeast, australiasoutheast, brazilsouth, canadacentral, canadaeast, centralindia, centralus, eastasia, eastus,
eastus2, francecentral, germanywestcentral, israelcentral, italynorth, japaneast, japanwest, jioindiawest, koreacentral, koreasouth, mexicocentral, northcentralus, northeurope, norwayeast, polandcentral, qatarcentral, southafricanorth, southcentralus, southeastasia, southindia, swedencentral,
switzerlandnorth, uaenorth, uksouth, ukwest, westcentralus, westeurope, westindia, westus, westus2, westus3, '.
│
```

It's doing the following call, and I can verify that it works when changing `api-version` to an older version:

``` http
GET https://management.azure.com/subscriptions/subscriptionId}/resourceGroups/rutgereventhubs-rg/providers/Microsoft.EventHub/namespaces/rutgereventhubs-hub-ns/networkRuleSets/default?api-version=2024-01-01
Content-Type: application/json; charset=utf-8
Authorization: Bearer {token}
```

Is there something on my end that needs to change? Or is this not supported yet?

**Comment by tombuildsstuff** [comment]
hey @rutgersc 

Apologies for the delayed reply to this one - just realised this hasn't had a reply.

Taking a look at the API response here (and re-running this today) it appears that the API version `2024-01-01` may have been delayed for some reason - the API Definitions can be published either ahead of time or retroactively after the API is published, and as such the Service Team would be the best folks to confirm the current status.

That said, checking the `Azure/azure-rest-api-specs` repository it appears that [there's a newer Preview version of this API available](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/eventhub/resource-manager/Microsoft.EventHub/preview/2024-05-01-preview) - but at this time I don't see that version listed in the API Response just yet, so I suspect it may not have been deployed at this point.

All that to say, from our side since `2024-01-01` doesn't appear to be publicly usable at this point in time (and may have been superseded) - and as such I suspect we're in a holding pattern until the new API version is published here, but we'll keep an eye out/will update this issue when this becomes available, so that we can get this added to this SDK.

Thanks!

**Comment by rutgersc** [comment]
Hi, thanks for the response! 

Not sure I fully understand. The repo you linked does have a stable version of [2024-01-01](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/eventhub/resource-manager/Microsoft.EventHub/stable/2024-01-01), it's just that it isn't actually deployed for some reason? Is there any other way to see what versions are supported besides running the api calls?

**Comment by rutgersc** [comment]
Closing this since things seem to now work with version `2024-01-01`.
